### PR TITLE
Feat: update user info during signin flow

### LINKED ISSUE #22: Feature for updating user info on signin
I have a case where I would love it if my Payload-users get updated data when they sign in. 

Currently got a flow for this working locally like this:

```
if (users.docs && users.docs.length) {
    user = users.docs[0];
    user = await payload.update({
        collection: collectionSlug,
        id: user.id,
        data: info,
        showHiddenFields: true,
    })
    user.collection = collectionSlug;
    user._strategy = 'oauth2';
}
```
The `info` contains up to date data fetched through the authorization flow.

Tried cloning the repo and replicating my code, but getting a type-error on this line:
`id: user.id`

Error:
`Property 'id' does not exist on type 'User & { collection?: any; _strategy?: any; }'.`

Guessing it's because there actually isn't a User collection with values being referenced? Tried addind `id: number` to the User interface, but that creates a whole bunch of other type issues. 

If anyone has any ideas on how to make this work I think it'd be a great addition to the plugin :)

### PR DESCRIPTION
**Pull request by augustgaukstad**
Added `payload.update` if user has been found in the Payload user-collection, so the user object in PayloadCMS syncs with potential new data from the userinfo-function.

Resolves #22

### CODE REVIEW

**Comment by Augigauki** [comment]
Hey @thgh - any ETA on when this might be merged? This feature would greatly enhance my Payload-app as I use app roles in Azure to control access control in PayloadCMS

**Comment by bote795** [comment]
i do think this should be an optional feature like pass in a field to enable this, not sure if everyone would want this.

**Comment by Augigauki** [comment]
Added a quick conditional to allow for choosing to update the user info on sign in or not.

**Comment by thgh** [comment]
Thanks for the PR! Released in v2.2.0 🎉

**Pull request merged**
